version: "3.3"
volumes:
  postgres:

services:
  app:
    build: .
    restart: always
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:14
    restart: always
    ports:
      - "${PG_PORT:-5432}:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
