version: "3.3"
services:
  app:
    build: .
    restart: always
    network_mode: host
    depends_on:
      - db
    env_file:
      - ".env"
  db:
    image: postgres
    restart: always
    ports:
      - "${PG_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: "sodijfsdofijposIJIJFEpdf"
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: